### ISSUE TITLE
Add option to indicate loot-table dead ends.

### ISSUE THREAD

**Issue by jakj** [Fasguy/MinecraftToolbox#27]
I request that empty loot tables (such as for fire) be replaced with a single piece of bedrock (to signify uselessness), so that (especially early game) there is a clear distinction between "no drop" and "need silk touch for drop".

**Comment by xsrvmy** [comment]
I'm not sure if having bedrock in the world is the best idea. Dropping a special item from the data pack would make more sense, or something useless like a clock.

**Comment by Fasguy** [comment]
I understand the concern about Bedrock roaming the world in the hands of players in a multiplayer setting. It's kind of a bummer, that block-placement can only be limited in adventure mode :/

Maybe just a piece of paper that says something along the lines of "sorry nothing" or "I.O.U." should be used instead, because i don't think that a clock really signifies a dead-end.
Then again, i could just title the clock "Time waster" or something like that.

**Comment by xsrvmy** [comment]
I just suggested clock because it can't be placed or be used for crafting
A custom datapack item is always an option
