### ISSUE TITLE
Random Assistant Curseforge link instead of GitHub

### ISSUE THREAD

**Issue by Bawnorton** [Fasguy/MinecraftToolbox#39]
Thanks for linking to my Random Assistant mod on your website, it would be appreciated if you could link it to the curseforge page instead of my GitHub page as Minecrafters tend to be more familiar with curseforge than GitHub and don't know where to go to download:
https://www.curseforge.com/minecraft/mc-mods/random-assistant

I was going to make a pull req but it doesn't seem that your GitHub repo is up to date with the current version of your website.

**Comment by Fasguy** [comment]
Yeah, i initially included the GitHub link, because i wasn't sure if you'd be uploading the mod to CurseForge while it's still in the "early" development stage, but didn't think far enough ahead to just ask you or... just check.

Also, regarding `I was going to make a pull req but it doesn't seem that your GitHub repo is up to date with the current version of your website.`
Could you tell me what made you think that? Both the `/trunk` and the `/dev` branch are on-par with the version i currently have up on my website, so there shouldn't be discrepancies.

**Comment by Bawnorton** [comment]
Thanks

> Could you tell me what made you think that? Both the /trunk and the /dev branch are on-par with the version i currently have up on my website, so there shouldn't be discrepancies.

Not sure if I'm doing something wrong as I am not familiar with angular but I couldn't find the link or project name anywhere in the project

<img width="1917" alt="Screenshot 2023-03-30 at 11 20 01 PM" src="https://user-images.githubusercontent.com/18416784/229040010-88c7d59e-49ff-47b8-a67c-8e60a05a63e2.png">

and grep came up empty.

<img width="697" alt="Screenshot 2023-03-30 at 11 29 58 PM" src="https://user-images.githubusercontent.com/18416784/229041084-c3c85793-a9e1-4b91-90a0-d73f0747f527.png">

**Comment by Fasguy** [comment]
Ah, yeah that makes sense.
The additional resources are actually part of the metadata for the version that has been selected, so they're part of the data.zip file.
I've updated the links really quick, you can check that in commit 7f12d31, if you want.
I'll update the website in a bit.
